/* Every building and prop here lives in its own package under src/buildings/<id>/; this file only re-exports them (maps and
   contracts import from here) plus the shared Placement, gridFeed, TINT and rng from src/buildings/_shared/base.ts. */
export { gridFeed, rng, TINT, type Placement } from '../buildings/_shared/base.ts';

export { gardenShed } from '../buildings/shed/parts/main.ts';
export { gardenWall } from '../buildings/garden-wall/parts/main.ts';
export { outhouse } from '../buildings/outhouse/parts/main.ts';
export { greenhouse } from '../buildings/greenhouse/parts/main.ts';
export { bungalow } from '../buildings/bungalow/parts/main.ts';
export { waterTower } from '../buildings/water-tower/parts/main.ts';
export { pumpHouse } from '../buildings/pump-house/parts/main.ts';
export { brickStack } from '../buildings/brick-stack/parts/main.ts';
export { siteOffice } from '../buildings/site-office/parts/main.ts';
export { van } from '../buildings/van/parts/main.ts';
export { car } from '../buildings/car/parts/main.ts';
export { warehouse } from '../buildings/warehouse/parts/main.ts';
export { pipeRack } from '../buildings/pipe-rack/parts/main.ts';
export { industrialChimney } from '../buildings/chimney/parts/main.ts';
export { mill } from '../buildings/mill/parts/main.ts';
export { cottageRow } from '../buildings/cottage-row/parts/main.ts';
export { overpass } from '../buildings/overpass/parts/main.ts';
export { busShelter } from '../buildings/bus-shelter/parts/main.ts';
export { towerBlock } from '../buildings/tower-block/parts/main.ts';
export { chipShop } from '../buildings/chipshop/parts/main.ts';
export { dump } from '../buildings/mixed-cache/parts/main.ts';
export { apartmentBlock } from '../buildings/apartment-block/parts/main.ts';
export { carPark } from '../buildings/car-park/parts/main.ts';
export { officeBlock } from '../buildings/office-block/parts/main.ts';
export { timberBarn } from '../buildings/barn/parts/main.ts';
export { chapel } from '../buildings/chapel/parts/main.ts';
export { rotunda } from '../buildings/rotunda/parts/main.ts';
export { spiralFolly } from '../buildings/spiral-stair/parts/main.ts';
export { stoneArchBridge } from '../buildings/arch-bridge/parts/main.ts';
export { trussBridge } from '../buildings/truss-bridge/parts/main.ts';
export { timberFrameHouse } from '../buildings/timber-frame-house/parts/main.ts';
export { brickByBrickWall } from '../buildings/brick-wall/parts/main.ts';
export { skyscraper } from '../buildings/skyscraper/parts/main.ts';
export { coolingTower } from '../buildings/cooling-tower/parts/main.ts';
export { latticePylon } from '../buildings/pylon/parts/main.ts';
export { factory } from '../buildings/sawtooth-factory/parts/main.ts';
export { stadiumStand } from '../buildings/stand/parts/main.ts';
export { towerCrane } from '../buildings/crane/parts/main.ts';
export { scaffoldTower } from '../buildings/scaffold-tower/parts/main.ts';
