/* GENERATED by scripts/gen-buildings.ts — do not edit. Run `npm run buildings`. */
import type { PieceSpec, PrefabView } from '../types.ts';
import type { Placement } from './_shared/base.ts';
import { assemble, type BuildingDef } from './assemble.ts';
import b_apartment_block from './apartment-block/def.ts';
import b_arch_bridge from './arch-bridge/def.ts';
import b_backdrop_tower from './backdrop-tower/def.ts';
import b_barn from './barn/def.ts';
import b_boiler_chimney from './boiler-chimney/def.ts';
import b_brick_stack from './brick-stack/def.ts';
import b_brick_wall from './brick-wall/def.ts';
import b_bungalow from './bungalow/def.ts';
import b_bus_shelter from './bus-shelter/def.ts';
import b_car from './car/def.ts';
import b_car_park from './car-park/def.ts';
import b_cathedral from './cathedral/def.ts';
import b_chapel from './chapel/def.ts';
import b_chapel_lite from './chapel-lite/def.ts';
import b_chimney from './chimney/def.ts';
import b_chipshop from './chipshop/def.ts';
import b_cooling_tower from './cooling-tower/def.ts';
import b_cottage_row from './cottage-row/def.ts';
import b_crane from './crane/def.ts';
import b_deptstore from './deptstore/def.ts';
import b_frame_under_construction from './frame-under-construction/def.ts';
import b_garden_wall from './garden-wall/def.ts';
import b_gasholder from './gasholder/def.ts';
import b_greenhouse from './greenhouse/def.ts';
import b_high_street_unit from './high-street-unit/def.ts';
import b_highrise from './highrise/def.ts';
import b_merchant_shed from './merchant-shed/def.ts';
import b_mill from './mill/def.ts';
import b_millworks from './millworks/def.ts';
import b_mixed_cache from './mixed-cache/def.ts';
import b_office_block from './office-block/def.ts';
import b_outhouse from './outhouse/def.ts';
import b_overpass from './overpass/def.ts';
import b_pipe_rack from './pipe-rack/def.ts';
import b_portal_shed from './portal-shed/def.ts';
import b_pump_house from './pump-house/def.ts';
import b_pylon from './pylon/def.ts';
import b_road_bridge from './road-bridge/def.ts';
import b_rotunda from './rotunda/def.ts';
import b_sawtooth_factory from './sawtooth-factory/def.ts';
import b_scaffold_tower from './scaffold-tower/def.ts';
import b_semi_pair from './semi-pair/def.ts';
import b_shed from './shed/def.ts';
import b_site_cabin from './site-cabin/def.ts';
import b_site_office from './site-office/def.ts';
import b_skyscraper from './skyscraper/def.ts';
import b_spiral_stair from './spiral-stair/def.ts';
import b_stadium from './stadium/def.ts';
import b_stand from './stand/def.ts';
import b_station from './station/def.ts';
import b_terrace from './terrace/def.ts';
import b_timber_frame_house from './timber-frame-house/def.ts';
import b_timber_house from './timber-house/def.ts';
import b_tower_block from './tower-block/def.ts';
import b_truss_bridge from './truss-bridge/def.ts';
import b_van from './van/def.ts';
import b_warehouse from './warehouse/def.ts';
import b_water_tower from './water-tower/def.ts';
import b_works_hall from './works-hall/def.ts';

export const BUILDINGS: Record<string, BuildingDef<any>> = {
  'apartment-block': b_apartment_block,
  'arch-bridge': b_arch_bridge,
  'backdrop-tower': b_backdrop_tower,
  'barn': b_barn,
  'boiler-chimney': b_boiler_chimney,
  'brick-stack': b_brick_stack,
  'brick-wall': b_brick_wall,
  'bungalow': b_bungalow,
  'bus-shelter': b_bus_shelter,
  'car': b_car,
  'car-park': b_car_park,
  'cathedral': b_cathedral,
  'chapel': b_chapel,
  'chapel-lite': b_chapel_lite,
  'chimney': b_chimney,
  'chipshop': b_chipshop,
  'cooling-tower': b_cooling_tower,
  'cottage-row': b_cottage_row,
  'crane': b_crane,
  'deptstore': b_deptstore,
  'frame-under-construction': b_frame_under_construction,
  'garden-wall': b_garden_wall,
  'gasholder': b_gasholder,
  'greenhouse': b_greenhouse,
  'high-street-unit': b_high_street_unit,
  'highrise': b_highrise,
  'merchant-shed': b_merchant_shed,
  'mill': b_mill,
  'millworks': b_millworks,
  'mixed-cache': b_mixed_cache,
  'office-block': b_office_block,
  'outhouse': b_outhouse,
  'overpass': b_overpass,
  'pipe-rack': b_pipe_rack,
  'portal-shed': b_portal_shed,
  'pump-house': b_pump_house,
  'pylon': b_pylon,
  'road-bridge': b_road_bridge,
  'rotunda': b_rotunda,
  'sawtooth-factory': b_sawtooth_factory,
  'scaffold-tower': b_scaffold_tower,
  'semi-pair': b_semi_pair,
  'shed': b_shed,
  'site-cabin': b_site_cabin,
  'site-office': b_site_office,
  'skyscraper': b_skyscraper,
  'spiral-stair': b_spiral_stair,
  'stadium': b_stadium,
  'stand': b_stand,
  'station': b_station,
  'terrace': b_terrace,
  'timber-frame-house': b_timber_frame_house,
  'timber-house': b_timber_house,
  'tower-block': b_tower_block,
  'truss-bridge': b_truss_bridge,
  'van': b_van,
  'warehouse': b_warehouse,
  'water-tower': b_water_tower,
  'works-hall': b_works_hall,
};

export const BUILDING_VARIANTS: { id: string; name: string; category: PrefabView['category']; base: string; params: Record<string, unknown> }[] =
  Object.values(BUILDINGS).flatMap((d) => [
    { id: d.id, name: d.name, category: d.category, base: d.id, params: {} },
    ...(d.variants ?? []).map((v) => ({ id: v.id, name: v.name, category: v.category ?? d.category, base: d.id, params: v.params as Record<string, unknown> })),
  ]);

export function building(id: string, placement: Placement & Record<string, unknown>): PieceSpec[] {
  const v = BUILDING_VARIANTS.find((b) => b.id === id);
  if (!v) throw new Error(`unknown building '${id}'`);
  return assemble(BUILDINGS[v.base], { ...placement, ...v.params });
}
