import { describeClaim, isClaimFile, parseClaim } from '../src/buildings/claims.ts';

declare const process: {
  argv: string[];
  getBuiltinModule(id: 'fs'): {
    readdirSync(path: string, opts: { withFileTypes: true }): { name: string; isDirectory(): boolean; isFile(): boolean }[];
    existsSync(path: string): boolean;
    writeFileSync(path: string, data: string): void;
    readFileSync(path: string, enc: 'utf8'): string;
  };
  getBuiltinModule(id: 'path'): { join(...parts: string[]): string; dirname(p: string): string; resolve(p: string): string };
  getBuiltinModule(id: 'url'): { fileURLToPath(u: string): string };
};
const { readdirSync, existsSync, writeFileSync, readFileSync } = process.getBuiltinModule('fs');
const { join, dirname, resolve } = process.getBuiltinModule('path');
const { fileURLToPath } = process.getBuiltinModule('url');

/* `--root <dir>` generates for another buildings folder (tests only). */
const ri = process.argv.indexOf('--root');
const ROOT = ri >= 0 ? resolve(process.argv[ri + 1]) : join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'buildings');
const candidates = readdirSync(ROOT, { withFileTypes: true })
  /* `_` folders are shared code; `zz-test-` folders are scratch packages the tests create and delete. */
  .filter((d) => d.isDirectory() && !d.name.startsWith('_') && !d.name.startsWith('zz-test-') && existsSync(join(ROOT, d.name, 'def.ts')))
  .map((d) => d.name).sort();
const VALID_ID = /^[a-z0-9][a-z0-9-]*$/;
const skipped = candidates.filter((n) => !VALID_ID.test(n));
if (skipped.length) console.warn(`WARNING: skipped building folders with invalid names (need ${VALID_ID}): ${skipped.map((n) => `'${n}'`).join(', ')}`);
const ids = candidates.filter((n) => VALID_ID.test(n));
const ident = (id: string) => 'b_' + id.replace(/[^a-z0-9]/gi, '_');
const src = `/* GENERATED by scripts/gen-buildings.ts — do not edit. Run \`npm run buildings\`. */
import type { PieceSpec, PrefabView } from '../types.ts';
import type { Placement } from './_shared/base.ts';
import { assemble, type BuildingDef } from './assemble.ts';
${ids.map((id) => `import ${ident(id)} from './${id}/def.ts';`).join('\n')}

export const BUILDINGS: Record<string, BuildingDef<any>> = {
${ids.map((id) => `  '${id}': ${ident(id)},`).join('\n')}
};

export const BUILDING_VARIANTS: { id: string; name: string; category: PrefabView['category']; base: string; params: Record<string, unknown> }[] =
  Object.values(BUILDINGS).flatMap((d) => [
    { id: d.id, name: d.name, category: d.category, base: d.id, params: {} },
    ...(d.variants ?? []).map((v) => ({ id: v.id, name: v.name, category: v.category ?? d.category, base: d.id, params: v.params as Record<string, unknown> })),
  ]);

export function building(id: string, placement: Placement & Record<string, unknown>): PieceSpec[] {
  const v = BUILDING_VARIANTS.find((b) => b.id === id);
  if (!v) throw new Error(\`unknown building '\${id}'\`);
  return assemble(BUILDINGS[v.base], { ...placement, ...v.params });
}
`;
const out = join(ROOT, 'registry.gen.ts');
const same = existsSync(out) && readFileSync(out, 'utf8') === src;
if (!same) writeFileSync(out, src);
console.log(`registry: ${ids.length} buildings${same ? ' (unchanged)' : ' (written)'}`);

const claims = ids.flatMap((id) => readdirSync(join(ROOT, id), { withFileTypes: true })
  .filter((d) => d.isFile() && isClaimFile(d.name))
  .map((d) => `${id}/${describeClaim(parseClaim(d.name, readFileSync(join(ROOT, id, d.name), 'utf8')))}`));
console.log(claims.length ? `active claims (${claims.length}):\n${claims.map((c) => `  ${c}`).join('\n')}` : 'active claims: none');
